### ISSUE TITLE
Can't write to CSV?

### ISSUE THREAD

**Issue by markdudlik** [youyanggu/groupme_stats#1]
Hi!

I have been trying really hard to get the script to download the history. The one time it worked all the way through, it didn't write to anything! Its a 1.2m post pull, which took a few hours. Now when i try to do the -c chatname.csv, I am getting this error. 

   File "groupme_stats-master/retrieve_msgs.py", line 184, in <module>
    main(args.all, args.group, args.csv, args.overwrite)
  File "groupme_stats-master/retrieve_msgs.py", line 170, in main
    count, _ = countMsgs(groups[group]['id'], csv_file=csv_file)
  File "groupme_stats-master/retrieve_msgs.py", line 146, in countMsgs
    wr.writerow([created_at.encode('utf-8'), user.encode('utf-8'), text.encode('utf-8')])
AttributeError: 'NoneType' object has no attribute 'encode'

Please help me get this to work!

**Comment by Ddfulton** [comment]
I also couldn't get it to write to a csv file, nothing in the directory after retrieve_msgs.py

**Comment by youyanggu** [comment]
Does it print out your messages if you turn csv mode off?

**Comment by Ddfulton** [comment]
How do I turn csv mode off?

**Comment by youyanggu** [comment]
Never mine, you can't from the command line. Try running it with the '-a'
flag:

*python retrieve_msgs.py [YOUR TOKEN] -a*

It should output to a csv file called temp.csv.

**Comment by budd3n** [comment]
I am getting the following when I try to write to a CSV file

File "C:\retrieve_msgs.py", line 186, in <module>
    main(args.all, args.group, args.csv, args.overwrite)
  File "C:\retrieve_msgs.py", line 161, in main
    for k, v in groups.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Please help!

**Comment by youyanggu** [comment]
You are using Python 3. The code supports Python 2. Change that
groups.iteritems() to groups.items().
