### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 19-20:ordinal not in range(128)

### ISSUE THREAD

**Issue by nave321** [youyanggu/groupme_stats#10]
It said the error was on line 57, where you set the name of the group being extracted to 

str(group['name']. 

To fix this, I just explicitly encoded it to unicode by changing the line to 

name = str(group['name'].encode('utf-8').strip())

**Comment by youyanggu** [comment]
oh yeah that should do it. Thanks for pointing it out!

**Comment by nave321** [comment]
Yeah no problem. The code worked on one access token, but when I used a different one, it threw that error.
