### ISSUE TITLE
Download Direct Messages

### ISSUE THREAD

**Issue by hasselhof** [youyanggu/groupme_stats#11]
I use GroupMe to do direct messaging as well, and it seems your tool only lets me download actual group messages. Is there a way to do direct messaging, too?

**Comment by youyanggu** [comment]
I don't think it does that right now. Would you like me to create that feature?

**Comment by hasselhof** [comment]
That would actually be amazing, since my reason for using your tool (amazing, by the way!) was to be able to search this extensive direct messaging history.

One other question - does it by any chance struggle with special characters in group names like "/"? One of my groups did not download, and I can only think that that is the reason.

**Comment by youyanggu** [comment]
Let me try to do that by the end of this week.

Yes it does - I just pushed a fix so if you pull now it should work!

**Comment by youyanggu** [comment]
I implemented direct messages. Just add '-d' to the command and everything else should be the same as before. Let me know if you run into any issues.

**Comment by hasselhof** [comment]
![grupme](https://cloud.githubusercontent.com/assets/17132376/13028170/e3474d4e-d234-11e5-9302-a491fde56ca8.JPG)

Is this the command to download direct messages? If so, I don't see evidence that it is writing to a csv, and I don't see a csv in the directory where the python script resides. Let me know what I am doing wrong. Thanks!

**Comment by hasselhof** [comment]
Dur, read the updated readme and realized it's -d -a. Sorry and thanks so much for adding this functionality!
