### ISSUE TITLE
Error when using group parameter

### ISSUE THREAD

**Issue by imjeffxp** [youyanggu/groupme_stats#12]
When I run the command:
python retrieve_msgs.py XXXXXXXXX -g '\xf0\x9f\x8f\x89 Fantasy Framily'

I get this error:

Traceback (most recent call last):
  File "retrieve_msgs.py", line 234, in <module>
    main(args.all, args.dm, args.group, args.csv, args.overwrite)
  File "retrieve_msgs.py", line 212, in main
    if group not in groups:
NameError: global name 'group' is not defined

**Comment by youyanggu** [comment]
Oops that's a bug. Change "group" to "group_name" on line 212 and you should be good. Alternatively, I pushed the fix so you can just pull again.
