### ISSUE TITLE
run_stats.py doesn't print out clean statistics when run without options

### ISSUE THREAD

**Issue by imjeffxp** [youyanggu/groupme_stats#13]

**Comment by imjeffxp** [comment]
adding description:

python run_stats.py output.csv
will print out something like:

('2014-12-29 15:25:07', 1), ('2015-12-03 13:13:44', 1), ('2014-11-11 14:14:40', 1), ('2015-10-01 08:09:45', 1), ('2014-12-22 21:38:25', 1), ('2015-09-21 16:35:21', 1), ('2016-01-15 13:41:39', 1), ('2014-09-05 22:57:19', 1), ('2015-10-07 17:51:53', 1), ('2015-12-08 09:03:07', 1), ('2015-10-22 10:37:45', 1), ('2015-10-28 23:19:34', 1), ('2015-10-11 15:10:02', 1), ('2015-11-08 07:18:29', 1), ('2015-11-15 15:17:54', 1), ('2016-02-09 16:46:47', 1), ('2015-09-18 16:56:42', 1), ('2015-10-26 16:20:39', 1), ('2015-10-29 10:38:23', 1), ('2015-10-29 10:38:27', 1), ('2015-08-20 10:42:02', 1), ('2015-07-15 22:18:03', 1), ('2015-10-26 16:20:33', 1), ('2015-01-01 10:27:23', 1), ('2015-10-26 16:20:36', 1), ('2015-11-18 09:26:41', 1), ('2014-10-23 18:49:29', 1), ('2015-09-26 18:52:13', 1), ('2015-09-10 23:40:16', 1), ('2015-12-14 15:05:03', 1), ('2014-12-04 23:12:39', 1), ('2015-09-10 23:40:11', 1), ('2015-11-16 20:17:16', 1), ('2014-10-28 17:02:00', 1), ('2015-08-26 22:47:01', 1), ('2015-08-26 22:47:02', 1)

**Comment by youyanggu** [comment]
Oh nice catch. I pushed the fix - let me know if the problem persists.
