### ISSUE TITLE
Help pulling just one group

### ISSUE THREAD

**Issue by cdonohue413** [youyanggu/groupme_stats#14]
Hey there,

First just wanted to say thanks for sharing this!! This is really cool and my friends are all so happy to finally have a way to pull history!!!!  But I'm hoping you can help me with something- I'm pretty new to python so maybe I'm just being dumb and missing something simple.   I can pull all of my groups history (i have like 6 total groups), but I only want to pull ONE of the groups history to csv.  Can you help me just pull one?  What should the request look like? 

Here is what I am doing and error messages I am getting- What do I need to change???

> python retrieve_msgs.py 'putting my access token here'

Then I get this:
Here is all the groups and their message counts:
[("Group Name1", 88577), ('Group Name2', 62778), ect.....]

Then I try to just pull Group Name1:
Here is what I am entering with error:  python retrieve_msgs.py -g "Group Name1"
usage: retrieve_msgs.py [-h] [-a] [-d] [-g GROUP] [-c CSV] [-o] token
     - Error: Too Few Arguments

All I want to pull and run is "Group Name1" to CSV- what would this pull search look like?

Thanks so much!

**Comment by youyanggu** [comment]
You forgot to add your access token at the end when calling the group.

Youyang
