### ISSUE TITLE
Empty Message Case

### ISSUE THREAD

**Issue by MrBuddhaBear** [youyanggu/groupme_stats#15]
When I backed up all of my messages with retrieve_msgs.py, one of the `msg` variables in the 
for loop on line 173 was:
```
msg = {   
    u'user_id': u'', 
    u'attachments': [], 
    u'source_guid': u'', 
    u'text': None, 
    u'created_at': -62135596800, 
    u'sender_id': u'', 
    u'sender_type': u'', 
    u'system': False, 
    u'favorited_by': [], 
    u'avatar_url': None, 
    u'group_id': u'4745311', 
    u'id': u'137584906799629655', 
    u'name': u''}
```
Because of the negative `created_at` field, the conversion to a datetime failed at line 179 in retrieve_msgs.py.
```
created_at = datetime.datetime.fromtimestamp(msg['created_at']).strftime('%Y-%m-%d %H:%M:%S')
```

Not sure if this is a problem with GroupMe's API or an unhandled message case or something else. 

Anyways, thanks for sharing!

**Comment by youyanggu** [comment]
I submitted the patch. Thanks for pointing it out!
