### ISSUE TITLE
How to do everything?

### ISSUE THREAD

**Issue by stinkystr5** [youyanggu/groupme_stats#18]
When you say run a command, what does that mean? Does that mean pull up terminal and copy and paste the commands or what? Sorry, I'm have a very basic understanding of computers, Im just doing this for fun

**Comment by youyanggu** [comment]
Do you have Mac or Windows?

**Comment by stinkystr5** [comment]
mac, I dont have python installed either

**Comment by stinkystr5** [comment]
so i'm downloading command line tool, then ill install python, and from then on im kinda lost but I still havent gotten there yet

**Comment by youyanggu** [comment]
You need to install Python 2.7 (Try Anaconda: https://www.continuum.io/downloads).

After that, get the access token as described in the directions. Lastly, type:

python retrieve_msgs.py <YOUR ACCESS TOKEN> -a -c output.csv

**Comment by youyanggu** [comment]
Oh you need to download the code and navigate to this folder in Terminal. type "cd /Users/yourname/whereever/this/code/folder/is"

**Comment by stinkystr5** [comment]
When you say download the code, do you mean press the download icon to download youyanggu/groupme_stats?

**Comment by youyanggu** [comment]
yup that's one way to do it.

**Comment by stinkystr5** [comment]
ok, im way too confused, i might just get a friend to do this for me. I tried opening anaconda but its just a bunch of symbols in a textedit document. The download site also said to type in "bash Anaconda2-4.0.0-MacOSX-x86_64.sh" in terminal after downloading it but it just says "no such file or directory"

**Comment by youyanggu** [comment]
Use this link: https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda2-4.0.0-MacOSX-x86_64.pkg
