### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by Matlefkofsky** [youyanggu/groupme_stats#19]
Mathews-MacBook-Pro:GroupmeStats MatLefkofsky$ python retrieve_msgs.py <MY_ACCESS_TOKEN> -g "MY_GROUP_NAME"

I keep returning no such file or directory...How can i fix this.  I am trying to pull all of the messages from one group and return them in a CSV that i can then run the stats program on.  Thanks.

**Comment by youyanggu** [comment]
You need to be in the same directory as the program "retrieve_msgs.py".

You also need to pass in the Token. See the Readme.

**Comment by Matlefkofsky** [comment]
<img width="571" alt="screen shot 2016-06-01 at 6 01 26 pm" src="https://cloud.githubusercontent.com/assets/18729824/15728624/47506516-2823-11e6-9b5a-3b2335e6de1f.png">

same problem. I whited out my Token but when i pass it through it returns the token followed by the colon and the same error.

**Comment by youyanggu** [comment]
Can you type "ls" and "python -V" show me the screenshot?

**Comment by Matlefkofsky** [comment]
<img width="448" alt="screen shot 2016-06-01 at 6 10 58 pm" src="https://cloud.githubusercontent.com/assets/18729824/15728760/378a3584-2824-11e6-824c-1878d841016a.png">

**Comment by youyanggu** [comment]
Oh, don't put brackets around your access token. That should do it.

**Comment by Matlefkofsky** [comment]
sorry to be a pest...

that just returns a 
>


...and then its like i have an open text field to type anything and have to quit out of terminal to try it again. Theres no CSV returned or anything at all returned really.

**Comment by youyanggu** [comment]
I don't think you're entering the right command. Please show me a screenshot?

**Comment by Matlefkofsky** [comment]
<img width="568" alt="screen shot 2016-06-01 at 6 30 01 pm" src="https://cloud.githubusercontent.com/assets/18729824/15729125/0cffd79e-2827-11e6-8f2f-6243f490ac01.png">

I think i'm entering it correctly.  Ive tried naming the parameters also and no luck. The "all direct messages" and "all groupme messages" commands are working for me but the specific group one just is not.  Thanks for your time also

**Comment by youyanggu** [comment]
You're using the wrong quotation mark for "Fantasy". The left one needs to be changed.

**Comment by youyanggu** [comment]
Were you able to run the code?

**Comment by Matlefkofsky** [comment]
Changing the left one didn't work--but changing both quotations around fantasy to single quotes did. Thanks!

**Comment by Matlefkofsky** [comment]
My last question is how would i see the average length of a user's post and also the average amount of likes on a user's post? I couldn't find this in the help section of the run_stats file.

**Comment by youyanggu** [comment]
Glad it worked. And sorry, that's not a feature right now. You can probably try using Excel to do the first task from the entire message dump.

**Comment by Matlefkofsky** [comment]
No problem. I just thought average length of a user's message was a feature because its listed in the 'Example usage:'

**Comment by youyanggu** [comment]
Oh you're right it is. Just add "--average" to the command and it should work.

**Comment by Matlefkofsky** [comment]
Thanks so much for all the help before.  I am curious if there is a way to see the top X amount of posts in terms of amount of favorites in a certain group?

**Comment by youyanggu** [comment]
Yup, just merged the feature added by mathieurolfo. Try it now. You will need to sort it on Excel afterwards for top X.
