### ISSUE TITLE
Output csv file makes every other row blank

### ISSUE THREAD

**Issue by mikkel14** [youyanggu/groupme_stats#22]
My output CSV file had every other line blank. Also, I had a fourth column in the CSV file that I couldn't make sense of. So the columns were: Group name, Timestamp, user, message, and then a  mystery row of numbers between 0 and 2. Ended up deleting this column and all blank rows using grep and then was able to use run_stats.py normally. 

I'm running Python 2.7.11 on Windows 10

**Comment by youyanggu** [comment]
Hmm that is quite weird. What is the command that you ran?

**Comment by mikkel14** [comment]
`python retrieve_msgs.py abc123MyAccessTokenHere -g "Awesome Group"`

**Comment by youyanggu** [comment]
That is strange. I just tried it and it works fine for me. I am using an older version of Python (2.7.6) on Mac so maybe that has something to do with it.

**Comment by mikkel14** [comment]
With Python 2.7.11, I fixed this by changing line 155 to` f = open(csv_file, "wb")` . This may differ with Python 3, you can read about it if you'd like [here](http://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row)

**Comment by youyanggu** [comment]
ah right! In Mac it defaults to bytes but it doesn't do that in Windows. I will make that change - thanks!
