### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by connor-b** [youyanggu/groupme_stats#23]
Any of the example commands I use from your instructions page returns an error in line 159 of the code

I've attached a screenshot here, with the access token scribbled out.

![image](https://cloud.githubusercontent.com/assets/20686604/17183500/c5899292-53f5-11e6-8d0e-3e13a6ff0fa1.png)

**Comment by youyanggu** [comment]
Are you using Python 3?

**Comment by pcrist13** [comment]
I'm having the same issue as well. Using python 3.4.

**Comment by youyanggu** [comment]
Sorry, it only supports Python 2.7 right now.

**Comment by pcrist13** [comment]
Okay, good to know. I believe I have it running with 2.7. Would you expect long execution times when a chat has a multi year history?
