### ISSUE TITLE
Help with run_stats

### ISSUE THREAD

**Issue by cdonohue413** [youyanggu/groupme_stats#24]
Hey,

I need some help using the run_stats command and getting it to provide output.  I can utilize the retrieve_msgs.py command just fine, and have a huge CSV file of our groupme output.  I would like to now use the run_stats option, but can't seem to figure out how to use it.

**Comment by cdonohue413** [comment]
![example](https://cloud.githubusercontent.com/assets/17204165/17556931/3eaeaf84-5ee3-11e6-8098-705656c7f3ba.JPG)

**Comment by youyanggu** [comment]
You should have 3 columns in your CSV file: time, name, and message. The error says you have less than 3 columns. Can you check why?
