### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by batorobe** [youyanggu/groupme_stats#25]
Hey man, I dunno if you're still supporting this or not.

File "retrieve_msgs.py", line 240, in <module>
main(args.all, args.dm, args.group, args.csv, args.overwrite)
File "retrieve_msgs.py", line 226, in main
count, _ = countMsgs(group_name, groups[group_name]['id'], direct_msgs, csv_file=csv_file)
File "retrieve_msgs.py", line 174, in countMsgs
for msg in msgs:
TypeError: 'NoneType' object is not iterable

At the beginning it says there are 30457 messages to be read, and stops at 8855.
And the last message read was
![image](https://cloud.githubusercontent.com/assets/5391898/17576895/786e32e4-5f3d-11e6-9b87-d491e444c595.png)

It also stopped reading messages at 8762. I've run it twice and it stops at the same spot

**Comment by youyanggu** [comment]
Not sure what happened, but it seems like the server returned no more messages.
