### ISSUE TITLE
I'm using Eclipse and it says "Too few arguments"

### ISSUE THREAD

**Issue by cheebnyc** [youyanggu/groupme_stats#28]
How do I fix this?

usage: retrieve_msgs.py [-h] [-a] [-d] [-g GROUP] [-c CSV] [-o] token
retrieve_msgs.py: error: too few arguments

I put my token into Line 24 and replaced the None in

TOKEN = None

**Comment by youyanggu** [comment]
Don't change the code. Just add your token to the command line:

`python retrieve_msgs.py [TOKEN]`

**Comment by cheebnyc** [comment]
On what compiler? I’m using Eclipse

Shiv Gidumal
Duke University 2017
(917) 301 6700
shiv.gidumal@gmail.com

**Comment by youyanggu** [comment]
You don't need a compiler. You just need python. Exit Eclipse and type the above command in your Terminal/Command Prompt.

**Comment by cheebnyc** [comment]
RuntimeError: Cannot retrieve groups. Is your token correct?


I put in my token but it still won’t work. Any advice?

**Comment by youyanggu** [comment]
It's saying there are no groups found. You don't need quotes or braces around your tokens, not sure if that is the issue...
