### ISSUE TITLE
Error on line 160

### ISSUE THREAD

**Issue by Dozer789** [youyanggu/groupme_stats#33]
When I try to use this, it throws this error no matter what I do. Even if I simply try to do python retrieve_msgs.py --help it still throws it.

```
File "tretieve_msgs.py", line 160
    print "Counting Messages for {} (Total: {})".format(group_name, totalCount)
                                               ^
SyntaxError: invalid syntax
```

**Comment by youyanggu** [comment]
Hi,

You are using Python 3. Unfortunately this snippet only works with Python 2, so I would try installing 2.7.
