### ISSUE TITLE
No Module named requests

### ISSUE THREAD

**Issue by butlerjoey** [youyanggu/groupme_stats#34]
I'm new to this, so bear with me...

I'm running the following command in command prompt (windows 7), python retrieve_msgs.py ******************************************************* -a -c output.cv.  Obviously, the astericks are just a placeholder for my access token.  

When I run that, I get the following error: "File "retrieve_msgs.py", line 9, in <module> import requests  ImportError: No module named requests"

Any idea on what might be wrong?

**Comment by youyanggu** [comment]
So you need to have Python's [requests](http://docs.python-requests.org/en/latest/) library. You can usually install it by typing `pip install requests`. Let me know if that doesn't work.

**Comment by butlerjoey** [comment]
That worked.  Thanks!
