### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by ricefazer** [youyanggu/groupme_stats#4]
I'm a novice Python user. This is the error I am receiving when I run retrieve_msgs.py
Any ideas on how to fix this?

**Comment by youyanggu** [comment]
Hi,

You need a token from GroupMe. Do you have one?

Youyang

**Comment by ricefazer** [comment]
Yes, my token starts with 41df and it is in one of the top lines of the picture I included. I was actually able to create a json file with another Python script. Could I use that to then run the stats Python script that you created?

Regards, 
Michael

**Comment by youyanggu** [comment]
You will probably be able to but unfortunately I don't think I will be able
to help you with that. Sorry.
