### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by kevinhuynh87** [youyanggu/groupme_stats#8]
Hi, I am a python rookie and am trying to get your script to work. Currently when running it just says:

usage: filename.py [-h] [-a] [-g GROUP] [-c CSV] [-o] token
filename.py: error: too few arguments

I have inputted my 40-char token like this.
TOKEN = 'XXXX'

And then I just run the script and I get the error. Any help is appreciated.

**Comment by youyanggu** [comment]
Try adding your token to the command, like this: 

```python retrieve_msgs.py TOKEN```
